### ISSUE TITLE
Replicate based LLM calls not working

### ISSUE THREAD

**Issue by mcnutter1** [a16z-infra/companion-app#81]
GPT based bots work but any replicate bots fail, API key is correct and billing is configured in Replicate.com

Error below: 

2023-07-25T13:09:59.268 proxy[17811e19b53498] iad [error] could not make HTTP request to instance: connection error: timed out

2023-07-25T13:10:32.281 app[17811e19b53498] iad [info] [llm/error] [1:llm:replicate] [90.17s] LLM run errored with error: "API request failed: Unprocessable Entity"

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] Error: API request failed: Unprocessable Entity

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] at Replicate.request (/app/.next/server/chunks/694.js:125:19)

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] at async Replicate.createPrediction (/app/.next/server/chunks/694.js:291:26)

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] at async Replicate.run (/app/.next/server/chunks/694.js:87:28)

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] at async RetryOperation._fn (/app/.next/server/chunks/985.js:20071:25) {

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] attemptNumber: 7,

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] retriesLeft: 0

2023-07-25T13:10:32.287 app[17811e19b53498] iad [info] }

**Comment by mcnutter1** [comment]
Issue resolved itself
